//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autodesk.ProductInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autodesk.ProductInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absolute.
        /// </summary>
        internal static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadsAtAxisDiscontinuities.
        /// </summary>
        internal static string AddLeadsAtToolAxisDiscontinuities {
            get {
                return ResourceManager.GetString("AddLeadsAtToolAxisDiscontinuities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadsOnShortLinks.
        /// </summary>
        internal static string AddLeadsToShortLinks {
            get {
                return ResourceManager.GetString("AddLeadsToShortLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveStartPoints.
        /// </summary>
        internal static string AllowStartPointToBeMoved {
            get {
                return ResourceManager.GetString("AllowStartPointToBeMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysRamp.
        /// </summary>
        internal static string AlwaysRamp {
            get {
                return ResourceManager.GetString("AlwaysRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxisDiscontinuityThreshold.
        /// </summary>
        internal static string AngularThreshold {
            get {
                return ResourceManager.GetString("AngularThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApproachDistance.
        /// </summary>
        internal static string ApproachDistance {
            get {
                return ResourceManager.GetString("ApproachDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcFittingRadius.Value.
        /// </summary>
        internal static string ArcFitRadius {
            get {
                return ResourceManager.GetString("ArcFitRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcFittingRadius.Active.
        /// </summary>
        internal static string ArcFitRapidMove {
            get {
                return ResourceManager.GetString("ArcFitRapidMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendMove.
        /// </summary>
        internal static string AutomaticallyExtend {
            get {
                return ResourceManager.GetString("AutomaticallyExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block_centre.
        /// </summary>
        internal static string BlockCentre {
            get {
                return ResourceManager.GetString("BlockCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boxed.
        /// </summary>
        internal static string Boxed {
            get {
                return ResourceManager.GetString("Boxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circle.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CircleDiameter.
        /// </summary>
        internal static string CircleDiameter {
            get {
                return ResourceManager.GetString("CircleDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circular_arc.
        /// </summary>
        internal static string CircularArc {
            get {
                return ResourceManager.GetString("CircularArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosedProfiles.
        /// </summary>
        internal static string ClosedSegments {
            get {
                return ResourceManager.GetString("ClosedSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.Cutting.Value.
        /// </summary>
        internal static string CuttingFeed {
            get {
                return ResourceManager.GetString("CuttingFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultLink[0].Type.
        /// </summary>
        internal static string DefaultLink {
            get {
                return ResourceManager.GetString("DefaultLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultLink[1].Type.
        /// </summary>
        internal static string DefaultLinkSecond {
            get {
                return ResourceManager.GetString("DefaultLinkSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint.MoveDirection.
        /// </summary>
        internal static string EndPointApproachAlong {
            get {
                return ResourceManager.GetString("EndPointApproachAlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint.Distance.
        /// </summary>
        internal static string EndPointApproachDistance {
            get {
                return ResourceManager.GetString("EndPointApproachDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint.Type.
        /// </summary>
        internal static string EndPointMethod {
            get {
                return ResourceManager.GetString("EndPointMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint.Position.X.
        /// </summary>
        internal static string EndPointPositionX {
            get {
                return ResourceManager.GetString("EndPointPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint.Position.Y.
        /// </summary>
        internal static string EndPointPositionY {
            get {
                return ResourceManager.GetString("EndPointPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPoint.Position.Z.
        /// </summary>
        internal static string EndPointPositionZ {
            get {
                return ResourceManager.GetString("EndPointPositionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend.
        /// </summary>
        internal static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extended.
        /// </summary>
        internal static string ExtendedMove {
            get {
                return ResourceManager.GetString("ExtendedMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExtensionLeadMoveTypes {
            get {
                return ResourceManager.GetString("ExtensionLeadMoveTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.FeedPerTooth.Value.
        /// </summary>
        internal static string FeedPerTooth {
            get {
                return ResourceManager.GetString("FeedPerTooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitLength.Active.
        /// </summary>
        internal static string FiniteRamp {
            get {
                return ResourceManager.GetString("FiniteRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitLength.Value.
        /// </summary>
        internal static string FiniteRampLength {
            get {
                return ResourceManager.GetString("FiniteRampLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstLeadIn.
        /// </summary>
        internal static string FirstLeadIn {
            get {
                return ResourceManager.GetString("FirstLeadIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_incr.
        /// </summary>
        internal static string FirstPoint {
            get {
                return ResourceManager.GetString("FirstPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_safe.
        /// </summary>
        internal static string FirstPointSafe {
            get {
                return ResourceManager.GetString("FirstPointSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT PAR TERSE &quot;ENTITY(&apos;{0}&apos;, &apos;{1}&apos;).{2}&quot;.
        /// </summary>
        internal static string GetParameterValue {
            get {
                return ResourceManager.GetString("GetParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GougeCheck.
        /// </summary>
        internal static string GougeCheck {
            get {
                return ResourceManager.GetString("GougeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horizontal_arc.
        /// </summary>
        internal static string HorizontalArc {
            get {
                return ResourceManager.GetString("HorizontalArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horizontal_arc_left.
        /// </summary>
        internal static string HorizontalArcLeft {
            get {
                return ResourceManager.GetString("HorizontalArcLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horizontal_arc_right.
        /// </summary>
        internal static string HorizontalArcRight {
            get {
                return ResourceManager.GetString("HorizontalArcRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incremental.
        /// </summary>
        internal static string Incremental {
            get {
                return ResourceManager.GetString("Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incr.
        /// </summary>
        internal static string IncrementalRamp {
            get {
                return ResourceManager.GetString("IncrementalRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computed.
        /// </summary>
        internal static string IsCalculated {
            get {
                return ResourceManager.GetString("IsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastLeadOut.
        /// </summary>
        internal static string LastLeadOut {
            get {
                return ResourceManager.GetString("LastLeadOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_incr.
        /// </summary>
        internal static string LastPoint {
            get {
                return ResourceManager.GetString("LastPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_safe.
        /// </summary>
        internal static string LastPointSafe {
            get {
                return ResourceManager.GetString("LastPointSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadIn[0].
        /// </summary>
        internal static string LeadIn {
            get {
                return ResourceManager.GetString("LeadIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadInExtension.
        /// </summary>
        internal static string LeadInExtension {
            get {
                return ResourceManager.GetString("LeadInExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.LeadInFactor.
        /// </summary>
        internal static string LeadInFactor {
            get {
                return ResourceManager.GetString("LeadInFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadIn[1].
        /// </summary>
        internal static string LeadInSecond {
            get {
                return ResourceManager.GetString("LeadInSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadOut[0].
        /// </summary>
        internal static string LeadOut {
            get {
                return ResourceManager.GetString("LeadOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadOutExtension.
        /// </summary>
        internal static string LeadOutExtension {
            get {
                return ResourceManager.GetString("LeadOutExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.LeadOutFactor.
        /// </summary>
        internal static string LeadOutFactor {
            get {
                return ResourceManager.GetString("LeadOutFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadOut[1].
        /// </summary>
        internal static string LeadOutSecond {
            get {
                return ResourceManager.GetString("LeadOutSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link[0].Type.
        /// </summary>
        internal static string Link1st {
            get {
                return ResourceManager.GetString("Link1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link[1].Type.
        /// </summary>
        internal static string Link2nd {
            get {
                return ResourceManager.GetString("Link2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link[2].Type.
        /// </summary>
        internal static string Link3rd {
            get {
                return ResourceManager.GetString("Link3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link[3].Type.
        /// </summary>
        internal static string Link4th {
            get {
                return ResourceManager.GetString("Link4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link[4].Type.
        /// </summary>
        internal static string Link5th {
            get {
                return ResourceManager.GetString("Link5th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LinkTypes {
            get {
                return ResourceManager.GetString("LinkTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongLink[0].Type.
        /// </summary>
        internal static string LongLink {
            get {
                return ResourceManager.GetString("LongLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongLink[1].Type.
        /// </summary>
        internal static string LongLinkSecond {
            get {
                return ResourceManager.GetString("LongLinkSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxMoveExtension.
        /// </summary>
        internal static string MaxMoveExtension {
            get {
                return ResourceManager.GetString("MaxMoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxZigAngle.
        /// </summary>
        internal static string MaxZigAngle {
            get {
                return ResourceManager.GetString("MaxZigAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveDirection.
        /// </summary>
        internal static string MoveDirection {
            get {
                return ResourceManager.GetString("MoveDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MoveType {
            get {
                return ResourceManager.GetString("MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on_surface.
        /// </summary>
        internal static string OnSurface {
            get {
                return ResourceManager.GetString("OnSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverlapDistance.
        /// </summary>
        internal static string OverlapDistance {
            get {
                return ResourceManager.GetString("OverlapDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.Plunging.Value.
        /// </summary>
        internal static string PlungingFeed {
            get {
                return ResourceManager.GetString("PlungingFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PM2016 {
            get {
                return ResourceManager.GetString("PM2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string PM2017 {
            get {
                return ResourceManager.GetString("PM2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pocket_centre.
        /// </summary>
        internal static string PocketCentre {
            get {
                return ResourceManager.GetString("PocketCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radial.
        /// </summary>
        internal static string Radial {
            get {
                return ResourceManager.GetString("Radial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        internal static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.Type.
        /// </summary>
        internal static string RampHeight {
            get {
                return ResourceManager.GetString("RampHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.Value.
        /// </summary>
        internal static string RampHeightValue {
            get {
                return ResourceManager.GetString("RampHeightValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveDirection.
        /// </summary>
        internal static string RetractAndApproachMoves {
            get {
                return ResourceManager.GetString("RetractAndApproachMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetractDistance.
        /// </summary>
        internal static string RetractDistance {
            get {
                return ResourceManager.GetString("RetractDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to safe.
        /// </summary>
        internal static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segment.
        /// </summary>
        internal static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segment_incr.
        /// </summary>
        internal static string SegmentIncremental {
            get {
                return ResourceManager.GetString("SegmentIncremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PAR &quot;ENTITY(&apos;{0}&apos;, &apos;{1}&apos;).{2}&quot; {3}.
        /// </summary>
        internal static string SetParameterNumaricValue {
            get {
                return ResourceManager.GetString("SetParameterNumaricValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PAR &quot;ENTITY(&apos;{0}&apos;, &apos;{1}&apos;).{2}&quot; &apos;{3}&apos;.
        /// </summary>
        internal static string SetParameterStringValue {
            get {
                return ResourceManager.GetString("SetParameterStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortLink[1].Type.
        /// </summary>
        internal static string ShortLinkSecond {
            get {
                return ResourceManager.GetString("ShortLinkSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThresholdDistance.
        /// </summary>
        internal static string ShortLinkThersholdToLong {
            get {
                return ResourceManager.GetString("ShortLinkThersholdToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortLink[0].Type.
        /// </summary>
        internal static string ShortLinkType {
            get {
                return ResourceManager.GetString("ShortLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skim.
        /// </summary>
        internal static string Skim {
            get {
                return ResourceManager.GetString("Skim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.Rapid.
        /// </summary>
        internal static string SkimFeed {
            get {
                return ResourceManager.GetString("SkimFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpindleSpeed.Value.
        /// </summary>
        internal static string SpindleSpeed {
            get {
                return ResourceManager.GetString("SpindleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPoint.MoveDirection.
        /// </summary>
        internal static string StartPointApproachAlong {
            get {
                return ResourceManager.GetString("StartPointApproachAlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPoint.Distance.
        /// </summary>
        internal static string StartPointApproachDistance {
            get {
                return ResourceManager.GetString("StartPointApproachDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPoint.Type.
        /// </summary>
        internal static string StartPointMethod {
            get {
                return ResourceManager.GetString("StartPointMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPoint.Position.X.
        /// </summary>
        internal static string StartPointPositionX {
            get {
                return ResourceManager.GetString("StartPointPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPoint.Position.Y.
        /// </summary>
        internal static string StartPointPositionY {
            get {
                return ResourceManager.GetString("StartPointPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPoint.Position.Z.
        /// </summary>
        internal static string StartPointPositionZ {
            get {
                return ResourceManager.GetString("StartPointPositionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepdown.
        /// </summary>
        internal static string Stepdown {
            get {
                return ResourceManager.GetString("Stepdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to straight.
        /// </summary>
        internal static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surface_normal_arc.
        /// </summary>
        internal static string SurfaceNormalArc {
            get {
                return ResourceManager.GetString("SurfaceNormalArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedRate.CuttingSpeed.Value.
        /// </summary>
        internal static string SurfaceSpeed {
            get {
                return ResourceManager.GetString("SurfaceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tangent.
        /// </summary>
        internal static string Tangent {
            get {
                return ResourceManager.GetString("Tangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        internal static string Tolerance {
            get {
                return ResourceManager.GetString("Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool_axis.
        /// </summary>
        internal static string ToolAxis {
            get {
                return ResourceManager.GetString("ToolAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.description.
        /// </summary>
        internal static string ToolDescription {
            get {
                return ResourceManager.GetString("ToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.diameter.
        /// </summary>
        internal static string ToolDiameter {
            get {
                return ResourceManager.GetString("ToolDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.flutes.
        /// </summary>
        internal static string ToolFlutes {
            get {
                return ResourceManager.GetString("ToolFlutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.identifier.
        /// </summary>
        internal static string ToolIndentifier {
            get {
                return ResourceManager.GetString("ToolIndentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.length.
        /// </summary>
        internal static string ToolLength {
            get {
                return ResourceManager.GetString("ToolLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.name.
        /// </summary>
        internal static string ToolName {
            get {
                return ResourceManager.GetString("ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.number.
        /// </summary>
        internal static string ToolNumber {
            get {
                return ResourceManager.GetString("ToolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolpath.
        /// </summary>
        internal static string ToolPath {
            get {
                return ResourceManager.GetString("ToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.tip_radius.
        /// </summary>
        internal static string ToolTipRadius {
            get {
                return ResourceManager.GetString("ToolTipRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool.type.
        /// </summary>
        internal static string ToolType {
            get {
                return ResourceManager.GetString("ToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical_arc.
        /// </summary>
        internal static string VerticalArc {
            get {
                return ResourceManager.GetString("VerticalArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZagAngle.Active.
        /// </summary>
        internal static string ZagAngle {
            get {
                return ResourceManager.GetString("ZagAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZagAngle.Value.
        /// </summary>
        internal static string ZagAngleMaximum {
            get {
                return ResourceManager.GetString("ZagAngleMaximum", resourceCulture);
            }
        }
    }
}
